# Generated by Django 5.2.1 on 2025-06-17 20:53

import Aplicacion.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Segmento de Empresa',
                'verbose_name_plural': 'Segmentos de Empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Empresa',
                'verbose_name_plural': 'Tipos de Empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=250, verbose_name='Razón Social')),
                ('tamaño', models.CharField(choices=[('MICRO', 'Microempresa (1-10 empleados)'), ('PEQUEÑA', 'Pequeña empresa (11-50 empleados)'), ('MEDIANA', 'Mediana empresa (51-250 empleados)'), ('GRANDE', 'Gran empresa (251+ empleados)')], max_length=10, verbose_name='Tamaño de la Empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Corporativo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('numero_empleados', models.PositiveIntegerField(verbose_name='Número de Empleados')),
                ('activa', models.BooleanField(default=True, verbose_name='Empresa Activa')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('requiere_autenticacion_2fa', models.BooleanField(default=False, verbose_name='Requiere Autenticación 2FA')),
                ('politica_contraseñas_estricta', models.BooleanField(default=True, verbose_name='Política de Contraseñas Estricta')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.segmentoempresa', verbose_name='Segmento')),
                ('tipo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Aplicacion.tipoempresa', verbose_name='Tipo de Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('edad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], max_length=50)),
                ('rol', models.CharField(choices=[('Usuario', 'Usuario'), ('Admin', 'Administrador')], default='Usuario', max_length=50)),
                ('groups', models.ManyToManyField(related_name='aplicacion_persona_set', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(related_name='aplicacion_persona_set', to='auth.permission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='DocumentoCajaFuerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=Aplicacion.models.documento_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'docm', 'xls', 'xlsx', 'xlsm', 'ppt', 'pptx', 'pptm', 'txt', 'rtf', 'odt', 'ods', 'odp', 'csv', 'xml', 'json', 'html', 'htm', 'md'])])),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('Personal', 'Personal'), ('Laboral', 'Laboral'), ('Financiero', 'Financiero'), ('Médico', 'Médico'), ('Legal', 'Legal'), ('Otro', 'Otro')], default='Personal', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tamano', models.PositiveIntegerField(editable=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('telefono_extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Extensión')),
                ('es_administrador_empresa', models.BooleanField(default=False, verbose_name='Administrador de Empresa')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, verbose_name='Puede Gestionar Usuarios')),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.empresa', verbose_name='Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
