# Generated by Django 5.2.4 on 2025-07-24 16:02

import Aplicacion.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)], verbose_name='Edad')),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], max_length=50, null=True, verbose_name='Género')),
                ('es_empresa', models.BooleanField(default=False, verbose_name='¿Es empresa?')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIT')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('rol', models.CharField(choices=[('Usuario', 'Usuario'), ('Admin', 'Administrador')], default='Usuario', max_length=50, verbose_name='Rol')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ultimo_acceso', models.DateTimeField(auto_now=True, verbose_name='Último acceso')),
                ('groups', models.ManyToManyField(blank=True, related_name='aplicacion_persona_set', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='aplicacion_persona_set', to='auth.permission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Aplicacion_persona',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCajaFuerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=Aplicacion.models.documento_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'docm', 'xls', 'xlsx', 'xlsm', 'ppt', 'pptx', 'pptm', 'txt', 'rtf', 'odt', 'ods', 'odp', 'csv', 'xml', 'json', 'html', 'htm', 'md'])])),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('Personal', 'Personal'), ('Laboral', 'Laboral'), ('Financiero', 'Financiero'), ('Medico', 'Médico'), ('Legal', 'Legal'), ('Otro', 'Otro')], default='Personal', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tamano', models.PositiveIntegerField(editable=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Caja Fuerte',
                'verbose_name_plural': 'Documentos Caja Fuerte',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
