# Generated by Django 5.2.1 on 2025-05-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentocajafuerte',
            old_name='tamaño',
            new_name='tamano',
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], default='Prefiero no decir', max_length=50),
            preserve_default=False,
        ),
    ]
