# Generated by Django 5.2.4 on 2025-07-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal'),
        ),
    ]
