# Generated by Django 4.2.11 on 2025-06-04 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_rename_tamaño_documentocajafuerte_tamano_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
    ]
