# Generated by Django 5.2.4 on 2025-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_persona_representante_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='empresa_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de la Empresa'),
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa_descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Empresa'),
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa_num_empleados',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Empleados'),
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa_pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País de la Empresa'),
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa_segmento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segmento de Empresa'),
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa_tamano',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tamaño de Empresa'),
        ),
        migrations.AddField(
            model_name='persona',
            name='empresa_tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Empresa'),
        ),
    ]
