# Generated by Django 5.2.4 on 2025-07-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_persona_empresa_ciudad_persona_empresa_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('-fecha_registro',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.TextField(blank=True, default='', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='empresa_ciudad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad de la Empresa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='empresa_descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción de la Empresa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='empresa_pais',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='País de la Empresa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='empresa_segmento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Segmento de Empresa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='empresa_tamano',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tamaño de Empresa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='empresa_tipo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo de Empresa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], default='', max_length=50, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='representante_legal',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Representante Legal'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sitio_web',
            field=models.URLField(blank=True, default='', verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono'),
        ),
    ]
