# Generated by Django 5.2.4 on 2025-07-24 16:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Empresa',
                'verbose_name_plural': 'Tipos de Empresa',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('segmento', models.CharField(choices=[('tecnologia', 'Tecnología'), ('salud', 'Salud'), ('educacion', 'Educación'), ('finanzas', 'Finanzas'), ('retail', 'Retail'), ('manufactura', 'Manufactura'), ('logistica', 'Logística'), ('energia', 'Energía'), ('construccion', 'Construcción'), ('turismo', 'Turismo'), ('entretenimiento', 'Entretenimiento'), ('otros', 'Otros')], max_length=50, verbose_name='Segmento')),
                ('tamaño', models.CharField(choices=[('micro', 'Microempresa (1-10 empleados)'), ('pequena', 'Pequeña empresa (11-50 empleados)'), ('mediana', 'Mediana empresa (51-250 empleados)'), ('grande', 'Gran empresa (251+ empleados)')], max_length=20, verbose_name='Tamaño')),
                ('pais', models.CharField(max_length=10, verbose_name='País')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('numero_empleados', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Empleados')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono Empresarial')),
                ('requiere_2fa', models.BooleanField(default=False, verbose_name='Requiere 2FA')),
                ('politica_estricta', models.BooleanField(default=False, verbose_name='Política Estricta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.tipoempresa', verbose_name='Tipo de Empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresa',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
